### ISSUE TITLE
Add ability to use a yml file to configure the updates

### ISSUE THREAD

**Issue by mustela** [DinkumInteractive/mwu#2]
We need to have the ability to pass a yml file with the sites configuration to the plugin. 

The yml would like: 

```
sites:
  exclude:
    - name: site4
  update:
    - name: site1
      env: dev
      report: true|false
      auto-commit: true|false
      confirm: true|false
      skip-backup: true|false
      auto-deploy: true|false
    - name: site2
      env: dev
      report: true|false
      auto-commit: true|false
      confirm: true|false
      skip-backup: true|false
      auto-deploy: true|false
```

`exclude` will not run any update on the site.

I've started with the change, so you can following it here: https://github.com/DinkumInteractive/mwu/pull/1
