### ISSUE TITLE
Add health-check

### ISSUE THREAD

**Issue by mustela** [DinkumInteractive/mwu#20]
Once the website is updated (only if there were some plugins updated), we should check if it is still up. We can do that in 2 ways, using curl or php. 

http://stackoverflow.com/questions/12747929/linux-script-with-curl-to-check-webservice-is-up

This is one is a nice approach, specially if we want to search some string in the page. But I wound't that required. 
http://www.catswhocode.com/blog/how-to-easily-monitor-your-web-server-using-php

If the site is down, we should ping a person in slack. We could add a new entry to the yml to add people, like

``` yml
slack_settings:
  channel: slack-channel-name
  username: slack-user-name
  icon_emoji: icon-for-chat
  url: https://hooks.slack.com/services/XXXXXXXXX/XXXXXXXXX/XXXXXXXXXXXXXXXXX
  on_error_notify_to:
   - user-slack-1
   - user-slack-2
```

And send the notification to those in case a website is down. 
This setting could be overwritten on each site. 

We could also use this setting to send a notification when terminus can't update a plugin

`advanced-custom-fields-pro      | 5.3.10      | 5.4.7       | Error`

Since that plugin is a private one, it should be updated manually.
